language: php

php:
    - 5.6

before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer install --prefer-source

script: vendor/bin/phpunit --configuration build

notifications:
  email: false

